# Generated by Django 4.2.16 on 2024-10-23 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NormalizedNameModel",
        ),
    ]
