stages:
    - linting
    - testing

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - pip install pep8-naming
        - pip install flake8_import_order
        - pip install flake8-quotes
        - flake8 --verbose .

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
        - black --check --diff .

django_test:
    stage: testing
    image: python:3.10
    script:
        - cd lyceum
        - python3 manage.py test
