stages:
  - linting

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - apt-get update && apt-get install -y gcc
        - pip install -r requirements.txt
        - flake8 --verbone .