stages:
  - linting

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
        - pip install -r requirements/prod.txt
        - pip install pep8-naming
        - pip install flake8_import_order
        - pip install flake8-quotes
        - flake8 --verbose .
        - pip install black
        - black --check --diff .