# Generated by Django 4.2.16 on 2024-11-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="О чем ваш фидбек",
                max_length=100,
                null=True,
                verbose_name="Название",
            ),
        ),
    ]
