# Generated by Django 4.2.16 on 2024-11-12 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0006_remove_feedback_mail_remove_feedback_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackauthor",
            name="feedback",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author",
                to="feedback.feedback",
            ),
        ),
    ]
