# Generated by Django 4.2.16 on 2024-11-13 08:47

from django.db import migrations, models
import feedback.models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_alter_feedbackauthor_feedback"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedbackauthor",
            options={"verbose_name": "автор", "verbose_name_plural": "авторы"},
        ),
        migrations.AlterModelOptions(
            name="feedbackfile",
            options={"verbose_name": "файл", "verbose_name_plural": "файлы"},
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "Получено"),
                    ("wip", "В обработке"),
                    ("ans", "Ответ дан"),
                ],
                default="new",
                help_text="Текущий этап обработки фидбека",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackfile",
            name="file",
            field=models.FileField(
                blank=True,
                upload_to=feedback.models.FeedbackFile.get_path,
                verbose_name="Файл",
            ),
        ),
    ]
