# Generated by Django 4.2.16 on 2024-10-16 19:55

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        (
            "catalog",
            "0001_squashed_0003_alter_category_options_alter_item_options_and_more",
        ),
        (
            "catalog",
            "0004_alter_category_is_published_alter_category_name_and_more",
        ),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите уникальное имя",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Элемент будет виден пользователям",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Слаг может состоять из латинских букв, цифр и нижнего подчеркивания",
                        max_length=200,
                        unique=True,
                        verbose_name="слаг",
                    ),
                ),
                (
                    "weight",
                    models.IntegerField(
                        default=100,
                        help_text="Введите число от 1 до 32767",
                        validators=[catalog.models.is_int_1_32767],
                        verbose_name="вес",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите уникальное имя",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Элемент будет виден пользователям",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Слаг может состоять из латинских букв, цифр и нижнего подчеркивания",
                        max_length=200,
                        unique=True,
                        verbose_name="слаг",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "тег",
                "verbose_name_plural": "теги",
            },
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите уникальное имя",
                        max_length=150,
                        unique=True,
                        verbose_name="название",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Элемент будет виден пользователям",
                        verbose_name="опубликовано",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Опишите товар",
                        validators=[catalog.models.contains_excellent_word],
                        verbose_name="текст",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="Выберите категорию",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.category",
                        verbose_name="категория",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        help_text="Можно выбрать несколько тегов",
                        related_name="items",
                        to="catalog.tag",
                        verbose_name="теги",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
    ]
