# Generated by Django 4.2.16 on 2024-10-23 11:18

import django.core.validators
from django.db import migrations, models

__all__ = ["Migration"]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.IntegerField(
                default=100,
                help_text="Введите число от 1 до 32767",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="вес",
            ),
        ),
    ]
