# Generated by Django 4.2.16 on 2024-10-24 20:20

from django.db import migrations, models
import django.db.models.deletion

__all__ = ["Migration"]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_imagemodel_item_main_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/", verbose_name="изображение товара"
                    ),
                ),
            ],
            options={
                "verbose_name": "главное изображение",
                "verbose_name_plural": "главные изображения",
            },
        ),
        migrations.CreateModel(
            name="UsualImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="catalog/", verbose_name="изображение товара"
                    ),
                ),
            ],
            options={
                "verbose_name": "обычное изображение",
                "verbose_name_plural": "обычные изображения",
            },
        ),
        migrations.RemoveField(
            model_name="item",
            name="main_image",
        ),
        migrations.DeleteModel(
            name="ImageModel",
        ),
        migrations.AddField(
            model_name="usualimage",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="catalog.item",
            ),
        ),
        migrations.AddField(
            model_name="mainimage",
            name="item",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="main_image",
                to="catalog.item",
            ),
        ),
    ]
