# Generated by Django 4.2.16 on 2024-10-28 17:57

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_alter_item_text"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="item",
            options={
                "ordering": ("name",),
                "verbose_name": "товар",
                "verbose_name_plural": "товары",
            },
        ),
        migrations.AlterModelManagers(
            name="item",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(default=False),
        ),
    ]
