# Generated by Django 4.2.16 on 2024-10-29 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_item_options_alter_item_managers_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="item",
            managers=[],
        ),
        migrations.AlterField(
            model_name="item",
            name="is_on_main",
            field=models.BooleanField(
                default=False, verbose_name="отображать на главной странице"
            ),
        ),
    ]
