# Generated by Django 4.2.16 on 2024-10-31 16:00

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        (
            "catalog",
            "0017_alter_galleryimage_item_alter_item_category_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="item",
            managers=[
                ("business_logic", django.db.models.manager.Manager()),
            ],
        ),
    ]
