# Generated by Django 4.2.16 on 2024-11-02 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_alter_item_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="item",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
