# Generated by Django 4.2.16 on 2024-11-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_item_create_date_item_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="create_date",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="item",
            name="update_date",
            field=models.DateField(auto_now=True),
        ),
    ]
