# Generated by Django 4.2.16 on 2024-11-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0020_alter_item_create_date_alter_item_update_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="create_date",
        ),
        migrations.RemoveField(
            model_name="item",
            name="update_date",
        ),
        migrations.AddField(
            model_name="item",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="время создания"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="время обновления"
            ),
        ),
    ]
